### ISSUE TITLE
Visual of a UIElement is not sized?

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/composition#10]
What I've noticed is the following piece of code will always return a `Size` of `(0,0)` for any `UIElement`.
```
var visual = ElementCompositionPreview.GetElementVisual(MyUIElement);
Debug.WriteLine($"Visual's size: {visual.Size}");
```
**Output**
> Visual's size: <0, 0>

Is this by design? I wonder what if I want to animate the `Size` of the element using *Composition Animations*?

**Comment by sernaj** [comment]
The preview API ElementCompositionPreview.GetElementVisual() currently returns a Visual with a size of 0,0 by design. Our recommendation is to use transforms instead of size animations where possible since transforms can be independently animated to provide a smooth visual experience.  As with XAML Storyboards, the size of XAML elements can’t be animated independently because it’s dependent on XAML layout and potentially app code running on the UI thread.  We are looking at options in the future to expand interop between XAML and composition APIs in this area.

**Comment by JustinXinLiu** [comment]
Thanks @sernaj . Just want to clarify, the *transforms* you mentioned is the `RenderTransform` in xaml framework right? Or is there one in Composition API that I am not aware of?

**Comment by sernaj** [comment]
Correct.

**Comment by JustinXinLiu** [comment]
Thanks for the clarification.
