### ISSUE TITLE
Hit testing disregards Orientation

### ISSUE THREAD

**Issue by tomzorz** [Microsoft/composition#21]
Hey

Is it possible that hit testing disregards Orientation? I thought that the Xaml side should be in sync with the visuals' position, but in my experience the PointerEntered/Exited events don't consider the change.

This can be observed here: https://github.com/tomzorz/Composition_fun/tree/master/Composition_Hotchkiss

Thanks,
Tamás

**Comment by pgills** [comment]
@tomzorz, sorry yesterday was a busy day. Thanks for a link to code example that is super helpful. Screenshots are helpful too if you can share them. We understand if you can't because you may/may not be working on something sensitive.

Anyway, when you say "Orientation" do you mean changing the `Visual.RotationInDegrees` property or the `Orientation` property on some XAML controls?

I think this is the scenario you are asking about:
"If I change the `RotationInDegrees` property on the `Visual` I get back from `ElementCompositionPreview.GetElementVisual(myElement)`, does hit testing and pointer events update accordingly?"

**Comment by tomzorz** [comment]
I wrote Orientation because I meant the Orientation property of a visual (which came from a xaml element). I recorded a short video where I explain the issue in detail: https://www.youtube.com/watch?v=wBQHIDBmW20 I hope this helps understanding my issue :)

**Comment by JustinXinLiu** [comment]
I actually have noticed the same hit testing issue on `InsetClip`. Would it be a good idea to disable hit testing on the areas that are clipped?

**Comment by tomzorz** [comment]
@JustinXinLiu clipping is debatable IMO, I can imagine scenarios where I'd want to have it and others where I don't. An "IsClippedAreaHitTestVisible" property could be the solution :bulb:

**Comment by JustinXinLiu** [comment]
@tomzorz I can totally live with that. :)

**Comment by sernaj** [comment]
We disregard hittesting support on Orientation via XAML interop by design as the XAML framework itself has no notion of quaternions right now, so this can't be carried through effectively. That means you need to roll your own as you would do in a frameworkless app or an island of composition Visuals inside a XAML app. For the InsetClip behavior, the current challenge there for updating hittesting is something you may have already noticed about InsetClip, to set one you need to explicitly set the size in our API as we don't pass that over from XAML in the current Interop. This makes passing back how the clip has changed to the framework for updated hittesting challenging. We're looking at better Interop in the next release and love to see feedback on this, like tomzorz's suggestion. Hope this helps to explain these issues.

**Comment by JustinXinLiu** [comment]
@sernaj Understood. At least for now I could break down the element that's clipped into smaller segments and manually set their `IsHitTestVisible` property in the XAML. Cheers.

**Comment by tomzorz** [comment]
@sernaj thanks for the explanation! :) I'd definitely love to see things like this carry over to the xaml world (or as I've discussed in the other ticket: get more / easier input support on the composition side.)

**Comment by sernaj** [comment]
Thanks again for all the feedback on this. I'm going the close issue but keep the feedback coming!
