### ISSUE TITLE
TransformComponents sample crashes on startup

### ISSUE THREAD

**Issue by mscherotter** [Microsoft/composition#31]
Running the TransformComponents sample crashes on startup:
"System.MissingMethodException: Method not found: 'System.Object Windows.UI.Xaml.Hosting.ElementCompositionPreview.GetContainerVisual(Windows.UI.Xaml.UIElement)'.\r\n   at TransformComponents.MainPage.MainPage_Loaded(Object sender, RoutedEventArgs e)"

Running from VS2015 update 1
Win10 64-bit 1511 (10586.164)

Any suggestions?

**Comment by robmikh** [comment]
Hi mscherotter,

It looks like you're running the sample from the 10240 directory, try running it from the 10586 directory. The composition API was "experimental" on the 10240 build of Windows 10, and we reccomend really only looking at the updated 10586 build. We've made API changes, which is why you're seeing the exception.

The old directory still exists mainly for archival purposes.

Sorry for the confusion!

**Comment by mscherotter** [comment]
You're right - I was running the wrong version.
